// API配置
// 开发环境：使用本地代理或直接访问本地Worker
// 生产环境：使用相对路径，通过Cloudflare Pages内部绑定Worker
const API_HOST = import.meta.env.DEV
  ? 'https://caiwu-backend.bingyizhou6u.workers.dev'
  : ''

// API Version Configuration
export const API_VERSION = 'v2'
const API_BASE = API_HOST

export const api = {
  base: API_BASE,
  health: `${API_BASE}/api/health`,
  auth: {
    login: `${API_BASE}/api/v2/auth/login`,
    loginPassword: `${API_BASE}/api/v2/auth/login`,
    logout: `${API_BASE}/api/v2/auth/logout`,
    activate: `${API_BASE}/api/v2/auth/activate`,
    verifyActivation: `${API_BASE}/api/v2/auth/activate/verify`,
    generateTotpForActivation: `${API_BASE}/api/v2/auth/generate-totp-for-activation`,
    requestMyResetLink: `${API_BASE}/api/v2/auth/request-my-reset-link`,
    verifyResetToken: `${API_BASE}/api/v2/auth/reset-password/verify`,
    resetPassword: `${API_BASE}/api/v2/auth/reset-password`,
    requestTotpReset: `${API_BASE}/api/v2/auth/mobile/request-totp-reset`,
    verifyTotpResetToken: `${API_BASE}/api/v2/auth/mobile/reset-totp/verify`,
    confirmTotpReset: `${API_BASE}/api/v2/auth/mobile/reset-totp/confirm`,
  },
  me: `${API_BASE}/api/v2/auth/me`,
  hq: `${API_BASE}/api/v2/hq`,
  departments: `${API_BASE}/api/v2/departments`,
  orgDepartments: `${API_BASE}/api/v2/org-departments`,
  orgDepartmentsById: (id: string) => `${API_BASE}/api/v2/org-departments/${id}`,
  positions: `${API_BASE}/api/v2/positions`,
  positionsAvailable: `${API_BASE}/api/v2/positions/available`,
  sites: `${API_BASE}/api/v2/sites`,
  sitesById: (id: string) => `${API_BASE}/api/v2/sites/${id}`,
  siteBills: `${API_BASE}/api/v2/site-bills`,
  siteBillsById: (id: string) => `${API_BASE}/api/v2/site-bills/${id}`,
  flows: `${API_BASE}/api/v2/flows`,
  flowsById: (id: string) => `${API_BASE}/api/v2/flows/${id}`,
  flowsNextVoucher: `${API_BASE}/api/v2/flows/next-voucher`,
  flowsUpdateVoucher: (id: string) => `${API_BASE}/api/v2/flows/${id}/voucher`,
  upload: {
    voucher: `${API_BASE}/api/v2/upload/voucher`,
    contract: `${API_BASE}/api/v2/rental-properties/upload/contract`,
  },
  vouchers: (path: string) => `${API_BASE}/api/v2/vouchers/${path}`,
  accounts: `${API_BASE}/api/v2/accounts`,
  accountsById: (id: string) => `${API_BASE}/api/v2/accounts/${id}`,
  accountTransfers: `${API_BASE}/api/v2/account-transfers`,
  accountTransfersById: (id: string) => `${API_BASE}/api/v2/account-transfers/${id}`,
  systemConfig: `${API_BASE}/api/v2/system-config`,
  currencies: `${API_BASE}/api/v2/currencies`,
  currenciesByCode: (code: string) => `${API_BASE}/api/v2/currencies/${code}`,
  categories: `${API_BASE}/api/v2/categories`,
  categoriesById: (id: string) => `${API_BASE}/api/v2/categories/${id}`,
  ar: {
    docs: `${API_BASE}/api/v2/ar/docs`,
    settlements: `${API_BASE}/api/v2/ar/settlements`,
    statement: `${API_BASE}/api/v2/ar/statement`,
    confirm: `${API_BASE}/api/v2/ar/confirm`,
  },
  reports: {
    departmentCash: `${API_BASE}/api/v2/reports/department-cash`,
    siteGrowth: `${API_BASE}/api/v2/reports/site-growth`,
    arSummary: `${API_BASE}/api/v2/reports/ar-summary`,
    arDetail: `${API_BASE}/api/v2/reports/ar-detail`,
    apSummary: `${API_BASE}/api/v2/reports/ap-summary`,
    apDetail: `${API_BASE}/api/v2/reports/ap-detail`,
    expenseSummary: `${API_BASE}/api/v2/reports/expense-summary`,
    expenseDetail: `${API_BASE}/api/v2/reports/expense-detail`,
    accountBalance: `${API_BASE}/api/v2/reports/account-balance`,
    borrowingSummary: `${API_BASE}/api/v2/reports/borrowing-summary`,
    borrowingDetail: (userId: string) => `${API_BASE}/api/v2/reports/borrowing-detail/${userId}`,
    employeeSalary: `${API_BASE}/api/v2/reports/employee-salary`,
    newSiteRevenue: `${API_BASE}/api/v2/reports/new-site-revenue`,
    annualLeave: `${API_BASE}/api/v2/reports/annual-leave`,
  },
  import: `${API_BASE}/api/v2/import`,
  auditLogs: `${API_BASE}/api/v2/audit-logs`,
  auditLogsCreate: `${API_BASE}/api/v2/audit-logs`, // POST to create log (e.g. for sensitive data access)
  auditLogsOptions: `${API_BASE}/api/v2/audit-logs/options`,
  auditLogsExport: `${API_BASE}/api/v2/audit-logs/export`,
  init: `${API_BASE}/api/v2/init-if-empty`,
  borrowings: `${API_BASE}/api/v2/borrowings`,
  borrowingsBalance: `${API_BASE}/api/v2/borrowings/balance`,
  repayments: `${API_BASE}/api/v2/repayments`,
  vendors: `${API_BASE}/api/v2/vendors`,
  vendorsById: (id: string) => `${API_BASE}/api/v2/vendors/${id}`,
  employees: `${API_BASE}/api/v2/employees`,
  employeesBatch: `${API_BASE}/api/v2/employees/batch`,
  employeesById: (id: string) => `${API_BASE}/api/v2/employees/${id}`,
  employeesResendActivation: (id: string) => `${API_BASE}/api/v2/employees/${id}/resend-activation`,
  employeesResetTotp: (id: string) => `${API_BASE}/api/v2/employees/${id}/reset-totp`,
  employeesRegularize: (id: string) => `${API_BASE}/api/v2/employees/${id}/regularize`,
  employeesLeave: (id: string) => `${API_BASE}/api/v2/employees/${id}/leave`,
  employeesRejoin: (id: string) => `${API_BASE}/api/v2/employees/${id}/rejoin`,
  employeesResetPassword: (id: string) => `${API_BASE}/api/v2/employees/${id}/reset-password`,
  employeeSalaries: `${API_BASE}/api/v2/employee-salaries`,
  employeeSalariesById: (id: string) => `${API_BASE}/api/v2/employee-salaries/${id}`,
  employeeSalariesBatch: `${API_BASE}/api/v2/employee-salaries/batch`,
  employeeAllowances: `${API_BASE}/api/v2/employee-allowances`,
  employeeAllowancesById: (id: string) => `${API_BASE}/api/v2/employee-allowances/${id}`,
  employeeAllowancesBatch: `${API_BASE}/api/v2/employee-allowances/batch`,
  allowancePayments: `${API_BASE}/api/v2/allowance-payments`,
  allowancePaymentsById: (id: string) => `${API_BASE}/api/v2/allowance-payments/${id}`,
  allowancePaymentsGenerate: `${API_BASE}/api/v2/allowance-payments/generate`,
  employeeLeaves: `${API_BASE}/api/v2/employee-leaves`,
  employeeLeavesById: (id: string) => `${API_BASE}/api/v2/employee-leaves/${id}`,
  employeeLeavesApprove: (id: string) => `${API_BASE}/api/v2/employee-leaves/${id}/status`,
  expenseReimbursements: `${API_BASE}/api/v2/expense-reimbursements`,
  expenseReimbursementsById: (id: string) => `${API_BASE}/api/v2/expense-reimbursements/${id}`,
  expenseReimbursementsApprove: (id: string) => `${API_BASE}/api/v2/expense-reimbursements/${id}/status`,
  expenseReimbursementsPay: (id: string) => `${API_BASE}/api/v2/expense-reimbursements/${id}/pay`,
  salaryPayments: `${API_BASE}/api/v2/salary-payments`,
  salaryPaymentsById: (id: string) => `${API_BASE}/api/v2/salary-payments/${id}`,
  salaryPaymentsGenerate: `${API_BASE}/api/v2/salary-payments/generate`,
  salaryPaymentsStatus: (id: string) => `${API_BASE}/api/v2/salary-payments/${id}/status`,
  salaryPaymentsAllocations: (id: string) => `${API_BASE}/api/v2/salary-payments/${id}/allocations`,
  salaryPaymentsAllocationsStatus: (id: string) => `${API_BASE}/api/v2/salary-payments/${id}/allocations/status`,
  salaryPaymentsEmployeeConfirm: (id: string) => `${API_BASE}/api/v2/salary-payments/${id}/employee-confirm`,
  salaryPaymentsFinanceApprove: (id: string) => `${API_BASE}/api/v2/salary-payments/${id}/finance-approve`,
  salaryPaymentsPaymentTransfer: (id: string) => `${API_BASE}/api/v2/salary-payments/${id}/payment-transfer`,
  salaryPaymentsPaymentConfirm: (id: string) => `${API_BASE}/api/v2/salary-payments/${id}/payment-confirm`,
  salaryPaymentsAllocationsApprove: (id: string) => `${API_BASE}/api/v2/salary-payments/${id}/allocations/approve`,
  ipWhitelist: `${API_BASE}/api/v2/ip-whitelist`,
  ipWhitelistById: (id: string) => `${API_BASE}/api/v2/ip-whitelist/${id}`,
  ipWhitelistBatch: `${API_BASE}/api/v2/ip-whitelist/batch`,
  ipWhitelistSync: `${API_BASE}/api/v2/ip-whitelist/sync`,
  ipWhitelistRule: `${API_BASE}/api/v2/ip-whitelist/rule`,
  ipWhitelistRuleCreate: `${API_BASE}/api/v2/ip-whitelist/rule/create`,
  ipWhitelistRuleToggle: `${API_BASE}/api/v2/ip-whitelist/rule/toggle`,
  myPermissions: `${API_BASE}/api/v2/my-permissions`,
  positionPermissions: `${API_BASE}/api/v2/position-permissions`,
  positionPermissionsById: (id: string) => `${API_BASE}/api/v2/position-permissions/${id}`,
  fixedAssets: `${API_BASE}/api/v2/fixed-assets`,
  fixedAssetsBatch: `${API_BASE}/api/v2/fixed-assets/batch`,
  fixedAssetsById: (id: string) => `${API_BASE}/api/v2/fixed-assets/${id}`,
  fixedAssetsCategories: `${API_BASE}/api/v2/fixed-assets/categories`,
  fixedAssetsDepreciations: (id: string) => `${API_BASE}/api/v2/fixed-assets/${id}/depreciations`,
  fixedAssetsTransfer: (id: string) => `${API_BASE}/api/v2/fixed-assets/${id}/transfer`,
  fixedAssetsPurchase: `${API_BASE}/api/v2/fixed-assets/purchase`,
  fixedAssetsSale: (id: string) => `${API_BASE}/api/v2/fixed-assets/${id}/sale`,
  fixedAssetsAllocate: (id: string) => `${API_BASE}/api/v2/fixed-assets/${id}/allocate`,
  fixedAssetsAllocations: `${API_BASE}/api/v2/fixed-assets/allocations`,
  fixedAssetsAllocationReturn: (id: string) => `${API_BASE}/api/v2/fixed-assets/allocations/${id}/return`,
  rentalProperties: `${API_BASE}/api/v2/rental-properties`,
  rentalPropertiesById: (id: string) => `${API_BASE}/api/v2/rental-properties/${id}`,
  rentalPropertiesAllocateDormitory: (id: string) => `${API_BASE}/api/v2/rental-properties/${id}/allocate-dormitory`,
  rentalPropertiesAllocations: `${API_BASE}/api/v2/rental-properties/allocations`,
  rentalPropertiesAllocationReturn: (id: string) => `${API_BASE}/api/v2/rental-properties/allocations/${id}/return`,
  rentalPayments: `${API_BASE}/api/v2/rental-payments`,
  rentalPaymentsById: (id: string) => `${API_BASE}/api/v2/rental-payments/${id}`,
  rentalPayableBills: `${API_BASE}/api/v2/rental-payable-bills`,
  rentalPayableBillsGenerate: `${API_BASE}/api/v2/rental-properties/generate-payable-bills`,
  rentalPayableBillsMarkPaid: (id: string) => `${API_BASE}/api/v2/rental-payable-bills/${id}/mark-paid`,
  dashboard: {
    stats: `${API_BASE}/api/v2/reports/dashboard/stats`,
  },
  // 个人中心
  my: {
    dashboard: `${API_BASE}/api/v2/my/dashboard`,
    leaves: `${API_BASE}/api/v2/my/leaves`,
    reimbursements: `${API_BASE}/api/v2/my/reimbursements`,
    borrowings: `${API_BASE}/api/v2/my/borrowings`,
    allowances: `${API_BASE}/api/v2/my/allowances`,
    assets: `${API_BASE}/api/v2/my/assets`,
    profile: `${API_BASE}/api/v2/my/profile`,
    attendance: {
      today: `${API_BASE}/api/v2/my/attendance/today`,
      clockIn: `${API_BASE}/api/v2/my/attendance/clock-in`,
      clockOut: `${API_BASE}/api/v2/my/attendance/clock-out`,
    },
  },
  // 审批
  approvals: {
    pending: `${API_BASE}/api/v2/approvals/pending`,
    history: `${API_BASE}/api/v2/approvals/history`,
    leaveApprove: (id: string) => `${API_BASE}/api/v2/approvals/leave/${id}/approve`,
    leaveReject: (id: string) => `${API_BASE}/api/v2/approvals/leave/${id}/reject`,
    reimbursementApprove: (id: string) => `${API_BASE}/api/v2/approvals/reimbursement/${id}/approve`,
    reimbursementReject: (id: string) => `${API_BASE}/api/v2/approvals/reimbursement/${id}/reject`,
    borrowingApprove: (id: string) => `${API_BASE}/api/v2/approvals/borrowing/${id}/approve`,
    borrowingReject: (id: string) => `${API_BASE}/api/v2/approvals/borrowing/${id}/reject`,
  },
}
